apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curl-cron-job
  namespace: kube-system
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-job
            image: alpine:3.9.4
            args:
            - /bin/sh
            - -c
            - apk add curl -y; curl -XPOST http://graylog3:12201/gelf -p0 -d '{"short_message":"Minä olen omena", "host":"alpine-k8s.org", "facility":"test", "_foo":"bar"}'
          restartPolicy: OnFailure
